// SERVER BASE URL
export const SERVER_URL = "http://localhost:8080";

// SERVER URL TO ADD USER
export const SERVER_ADD_USER_URL = SERVER_URL + "/demo/add";

// SERVER URL TO CHECK IF A USER WITH HIS ENCRYPTED PASSWORD IS ON THE BD
export const SERVER_CHECK_USER_URL = SERVER_URL + "/demo/checkPassword";

// SERVER URL TO ADD CREDENTIAL
export const SERVER_ADD_CREDENTIAL = SERVER_URL + "credentials/add";

// SERVER URL TO ADD CREDENTIAL
export const SERVER_GET_CREDENTIALS = SERVER_URL + "credentials/getAll";