// ---- APP VARIABLES ----

// SERVICE NAME FOR THE MASTER KEY TO USE ON KEYTAR
export const SERVICE_MASTER_KEY = "passwordManager_MasterKey";

// SERVICE NAME TO STORE THE EMAIL
export const SERVICE_EMAIL = "userEmail";

// SERVICE NAME FOR THE AUTHKEY TO USE ON KEYTAR
export const SERVICE_AUTH_KEY = "passwordManager_AuthKey";

// NUMBER OF ITERATIONS FOR THE CREATION OF THE DERIVATED KEY
export const ITERATIONS_PBKDF2 = 600000;

// TIME THAT THE CLIENT TAKES TO REMOVE THE MESSAGE
export const TIMING = 2000;

// ---- APP REQUIRED URLS ----

// SERVER BASE URL
const SERVER_URL = "https://blackvault-app-cpese4a6c4avhwaq.francecentral-01.azurewebsites.net";

// SERVER USER ACTIONS URL
const SERVER_USER_ACTIONS_URL = SERVER_URL + "/user";

// SERVER CREDENTIALS ACTIONS URL
const SERVER_CREDENTIALS_ACTIONS_URL = SERVER_URL + "/credentials";

// SERVER URL TO ADD USER
export const SERVER_USER_SIGNUP = SERVER_USER_ACTIONS_URL + "/signup";

// SERVER URL TO CHECK IF A USER WITH HIS ENCRYPTED PASSWORD IS ON THE BD
export const SERVER_USER_LOGIN = SERVER_USER_ACTIONS_URL + "/login";

// SERVER URL TO OBTAIN ALL THE CREDENTIALS FROM THE BD
export const SERVER_OBTAIN_USER_CREDENTIALS = SERVER_CREDENTIALS_ACTIONS_URL + "/getall";

// SERVER URL TO ADD A SPECIFIC CREDENTIAL FROM THE BD
export const SERVER_ADD_CREDENTIAL = SERVER_CREDENTIALS_ACTIONS_URL + "/add";

// SERVER URL TO DELETE A SPECIFIC CREDENTIAL FROM THE BD
export const SERVER_DELETE_CREDENTIAL = SERVER_CREDENTIALS_ACTIONS_URL + "/deleteAll";

// SERVER URL TO EDIT A SPECIFIC CREDENTIAL FROM THE BD
export const SERVER_EDIT_CREDENTIAL = SERVER_CREDENTIALS_ACTIONS_URL + "/edit";